# Generated by Django 4.2.4 on 2023-09-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_meal_category_meal_kitchen_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='images',
        ),
    ]
