# Generated by Django 4.2.4 on 2023-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_rename_image_photo_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Кухня'),
        ),
    ]
