# Generated by Django 4.2.6 on 2023-10-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_remove_customer_email_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='meal',
            new_name='product',
        ),
    ]
