# Generated by Django 4.2.6 on 2023-10-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_rename_meal_orderproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('data', models.DateTimeField()),
                ('time', models.TimeField()),
                ('people_quantity', models.IntegerField()),
                ('message', models.TextField(default='Пусто')),
                ('booking_time', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки сообщения')),
            ],
        ),
    ]
