# Generated by Django 4.2.6 on 2023-10-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_booking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='checked_booking',
            field=models.BooleanField(default=False, verbose_name='Проверка брони'),
        ),
    ]
